services:
  - type: web
    name: kfc-voice-assistant
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    # Native packages installation
    buildPacks:
      - url: https://github.com/jonathanong/heroku-buildpack-ffmpeg-latest.git