services:
  - type: web
    name: RAG_Based_AI_AGENT-1
    env: python
    plan: free

    pythonVersion: 3.11

    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn render_app:app --bind 0.0.0.0:$PORT
